//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kres.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DersProgrami
    {
        public int DersProgramiID { get; set; }
        public Nullable<int> DersID { get; set; }
        public Nullable<int> OgretmenID { get; set; }
        public Nullable<int> SinifID { get; set; }
        public Nullable<System.DateTime> Gun { get; set; }
        public Nullable<System.TimeSpan> BaslangicSaat { get; set; }
        public Nullable<System.TimeSpan> BitisSaat { get; set; }
    
        public virtual ders ders { get; set; }
        public virtual ogretmen ogretmen { get; set; }
        public virtual siniflar siniflar { get; set; }
    }
}
