//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kres.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanici
    {
        public int kullaniciID { get; set; }
        public string mail { get; set; }
        public string sifre { get; set; }
        public Nullable<bool> durum { get; set; }
    }
}
