//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kres.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ogrencisinif
    {
        public int ogrencisinifID { get; set; }
        public Nullable<int> ogrenciID { get; set; }
        public Nullable<int> sinifID { get; set; }
    
        public virtual ogrenci ogrenci { get; set; }
        public virtual siniflar siniflar { get; set; }
    }
}
