//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kres.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ogrenci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ogrenci()
        {
            this.ogrencisinif = new HashSet<ogrencisinif>();
            this.ogrenciveli = new HashSet<ogrenciveli>();
        }
    
        public int ogrenciID { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public Nullable<bool> cinsiyet { get; set; }
        public Nullable<System.DateTime> dogumtarihi { get; set; }
        public Nullable<int> tcno { get; set; }
        public Nullable<int> ogrencino { get; set; }
        public Nullable<bool> durumu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ogrencisinif> ogrencisinif { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ogrenciveli> ogrenciveli { get; set; }
    }
}
