//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kres.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class veli
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public veli()
        {
            this.ogrenciveli = new HashSet<ogrenciveli>();
        }
    
        public int veliID { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public string tcno { get; set; }
        public Nullable<bool> cinsiyet { get; set; }
        public string adres { get; set; }
        public string tel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ogrenciveli> ogrenciveli { get; set; }
    }
}
